\documentclass{article}
\usepackage{graphicx}
\usepackage{microtype}
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}
\usepackage{lmodern}
\usepackage{geometry}
\usepackage{authblk}
\usepackage{float}
\usepackage{parskip}
\usepackage{caption}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\usepackage[table]{xcolor}
\bibliographystyle{unsrt}

\begin{document}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(concordance = TRUE, comment = NA)
options(scipen = 1, digits = 2, warn = -1, stringsAsFactors = FALSE,
        width = 82)
@

\title{\texttt{ASpediaFI}: Functional Interaction Analysis of AS Events}

\author[1]{Doyeong Yu}

\affil[1]{Bioinformatics Branch, Research Institute,
National Cancer Center, Gyeonggi-do, Republic of Korea}

\date{}
\maketitle
\tableofcontents
\pagebreak
%------------------------------------------------------------
\section{Introduction}
%------------------------------------------------------------
Alternative splicing (AS) is a key contributor to transcriptome and phenotypic
diversity. There are hundreds of splicing factors regulating
AS events which have a significant impact on diverse biological functions.
However, it is challenging to identify functional events related to a specific
splicing factor among thousands of them and explore their
associations with genes and pathways. We developed an R package
\texttt{ASpediaFI} for a systematic and integrative analysis of
alternative splicing events and their functional interactions.

\begin{center}
\includegraphics{Figure1.png}
\captionof{figure}{Analytic workflow of \texttt{ASpediaFI}}
\end{center}

Figure 1 shows the analytic workflow of \texttt{ASpediaFI}. The workflow
consists of the following steps:
\begin{enumerate}
\item Annotate and quantify AS events.
\item Prepare gene expression quantification, a gene-gene interaction
network, and pathway gene sets.
\item Construct a heterogeneous network comprising gene, AS event, and pathway
nodes.
\item Run DRaWR on the heterogeneous network to rank AS events and pathways
for their relevance to a splicing factor or a gene set of interest.
\end{enumerate}
At the end of the workflow, a relevant subnetwork and a ranked list of AS events
and pathways will be generated for further analysis and visualization.

%------------------------------------------------------------
\section{Installation}
%------------------------------------------------------------
To install \texttt{ASpediaFI}, enter the following commands:
<<Install,message=FALSE,eval=FALSE>>=
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ASpediaFI")
@

\pagebreak

%------------------------------------------------------------
\section{Package contents and overview}
%------------------------------------------------------------

%------------------------------------------------------------
\subsection{Overview of \texttt{ASpediaFI}}
%------------------------------------------------------------
\texttt{ASpediaFI} provides the following functionalities:
\begin{itemize}
\item AS event detection and annotation
\item AS event quantification
\item Functional interaction analysis of AS events
\item Visualization of AS events and pathways
\end{itemize}
This package uses a reference class \texttt{ASpediaFI} as a wrapper of its
functionalities (methods) and a container of inputs and outputs
(fields).
<<LoadPackage,message=FALSE>>=
#Load the ASpediaFI package
library(ASpediaFI)

#Fields of the ASpediaFI reference class
ASpediaFI$fields()
@
The \texttt{ASpediaFI} reference class contains the following fields:
\begin{itemize}
\item \texttt{samples}: a data frame containing information about samples. The
first three columns should be names, BAM file paths, and conditions.
\item \texttt{events}: a list of AS events extracted from a GTF file.
\item \texttt{psi}: a \texttt{SummarizedExperiment} object containing PSI values
of AS events.
\item \texttt{gtf}: a \texttt{GRanges} object containing genomic features
extracted from a GTF file.
\item \texttt{network}: an \texttt{igraph} object containing a query-specific
subnetwork as a result of DRaWR.
\item \texttt{gene.table}, \texttt{as.table}, \texttt{pathway.table}: data
frames containing gene nodes, AS event nodes, and pathway nodes.
\end{itemize}

<<Methods,message=FALSE>>=
#Methods of the ASpediaFI reference class
setdiff(ASpediaFI$methods(), setRefClass("default")$methods())
@
Other than default methods provided for all reference classes,
the \texttt{ASpediaFI} reference class includes the following methods:
\begin{itemize}
\item \texttt{detect}: detects AS events from a GTF file and save it in the
\texttt{events} field. Also extract features from a GTF file and save in the
\texttt{gtf} field.
\item \texttt{quantify}: computes PSI values of AS events from BAM files
specified in the \texttt{samples} field.
\item \texttt{analyze}: constructs a heterogeneous network of genes, AS events,
and pathways and performs DRaWR.
\item \texttt{visualize}: visualizes AS event or pathway nodes.
\end{itemize}

\pagebreak

%------------------------------------------------------------
\subsection{Case study: SF3B1 mutation in myelodysplastic syndrome}
%------------------------------------------------------------
In this vignette, we will explore all these functionalities using a
dataset of myelodysplastic syndrome (MDS) patients from the study GSE114922 [1].
This dataset contains 82 MDS patient samples, 28 of which harbored SF3B1
mutations. The RNA-Seq reads from the GEO database were aligned to the
GRCh38 genome using STAR and quantified using RSEM.

SF3B1 is one of the most frequently mutated splicing factor in MDS, and
the study have shown its association with AS events of genes involved in
heme metabolism. In the following sections, we will walk through the
\texttt{ASpediaFI} workflow shown in Figure 1 to identify AS events associated
with SF3B1 mutation and explore their functional interactions.

%------------------------------------------------------------
\section{Workflow}
%------------------------------------------------------------

%------------------------------------------------------------
\subsection{Input data preparation}
%------------------------------------------------------------
To begin, we instantiate the \texttt{ASpediaFI} class and obtain a list of
AS event annotations from a GRCh38 GTF file using the \texttt{detect} method.
Due to file size limitations, we extract AS event annotations from a subset of
GRCh38 GTF file provided in the \texttt{extdata} directory of the package.
<<detectEvent,message=FALSE>>=
#Instantiate the ASpediaFI reference class
GSE114922.ASpediaFI <- ASpediaFI()

#Detect and annotate AS events from a subset of the hg38 GTF file
gtf <- system.file("extdata/GRCh38.subset.gtf", package = "ASpediaFI")
GSE114922.ASpediaFI$detect(gtf.file = gtf, num.cores = 1)
sapply(GSE114922.ASpediaFI$events, length)
head(GSE114922.ASpediaFI$events$SE)
@
The \texttt{detect} method identifies five types of AS events:
\begin{itemize}
\item A5SS (alternative 5' splice site)
\item A3SS (alternative 3' splice site)
\item SE (skipped exon)
\item MXE (mutually exclusive exon)
\item RI (retained intron)
\end{itemize}
A list of AS event annotations contains Ensembl ID, chromosome, strand, genomic
coordinates of exons, and AS event ID. AS event ID is written in the format of
[gene symbol]:[event type]:[chromosome]:[genomic coordinates of exon boundaries]
, as defined by ASpedia. The \texttt{detect} method also extracts genomic
features from a GTF file and save in a \texttt{gtf} field as a \texttt{GRanges}
object for the visualization of AS events.

Next, we quantify AS events from BAM files using the \texttt{quantify} method.
The \texttt{quantify} method requires the \texttt{samples} field to have three
columns in the following order: name (sample ID), path (BAM file path), and
condition (sample condition). Also, a type of RNA-Seq reads (single or paired),
read length, insert size, and a minimum number of reads mapped to a given exon
need to be specified. At this point, we compute PSI values from a subset of
one BAM file for demonstration. The \texttt{quantify} method saves PSI values
in the \texttt{psi} field as a \texttt{SummarizedExperiment} object with sample
information. Note that row names of PSI values are AS event IDs.
<<quantifyEvent,message=FALSE>>=
#Compute PSI values of AS events
bam <- system.file("extdata/GSM3167287.subset.bam", package = "ASpediaFI")
GSE114922.ASpediaFI$samples <- data.frame(name = "GSM3167287", path = bam,
                                          condition = "")
GSE114922.ASpediaFI$quantify(read.type = "paired", read.length = 100,
                             insert.size = 300, min.reads = 3, num.cores = 1)
tail(assays(GSE114922.ASpediaFI$psi)[[1]])
@

In addition to AS event annotations and quantifications, the following are
required for network reconstruction:
\begin{itemize}
\item a named list of pathway gene sets
\item an \texttt{igraph} object containing a gene-gene interaction network
\item a matrix or \texttt{SummarizedExperiment} object containing gene
expression profiles (FPKM)
\end{itemize}
If the first two inputs are not given, \texttt{ASpediaFI} uses a combined list
of HALLMARK, KEGG, and REACTOME pathway gene sets and a network with gene
interactions collected from BIND, DIP, HPRD, and REACTOME. Gene expression
quantifications must be prepared by the user using quantification tools such as
RSEM and Cufflinks. Here, we use gene expression profiles of MDS patients
stored in the package as an example dataset. Since we need sample information
and AS event quantifications for all samples, we also load the example dataset
containing PSI values and sample information to update the \texttt{psi} and
\texttt{samples} fields.
<<loadData,message=FALSE>>=
#Load PSI and gene expression data
data("GSE114922.fpkm")
data("GSE114922.psi")

#Update the "samples" and "psi" fields
GSE114922.ASpediaFI$psi <- GSE114922.psi
GSE114922.ASpediaFI$samples <- as.data.frame(colData(GSE114922.psi))

head(GSE114922.ASpediaFI$samples)
@

%------------------------------------------------------------
\subsection{Functional interaction analysis of AS events}
%------------------------------------------------------------
The \texttt{analyze} method performs data preprocessing, network construction
and DRaWR (Discriminative Random Walk with Restart) [2]. AS event and gene
expression quantifications, a gene-gene interaction network, and pathway gene
sets are  used to construct a heterogeneous network composed of gene, AS event,
and pathway nodes. DRaWR is then applied to identify AS events and pathways
associated with a gene set of interest.

The DRaWR algorithm consists of two stages of random walk with restart (RWR).
RWR is run on the heterogeneous network twice in the first stage, one with
a query gene set and another with all genes as the restart set. AS events and
pathways are ranked by the difference between the converged probability
distributions in two times of RWR. In the second stage, RWR is run on a
subnetwork composed of all gene nodes and top \textit{k} ranked feature
(AS event or pathway) nodes to obtain final rankings of genes and features.

As the DRaWR algorithm requires a query gene set as input, we first perform
t-test on the gene expression dataset to detect genes differentially expressed
in SF3B1-mutated samples. These DEGs are used as a query to identify AS events
and pathways closely related to SF3B1 mutation. If a query is given as a
character vector, all genes in the query have equal weights. The user can
attribute distinct weights by providing a data frame containing the weights
in the second column as a query.
<<prepareQuery,message=FALSE>>=
#Choose query genes based on differential expression
pvalues <- apply(log2(GSE114922.fpkm + 1), 1, function(x)
    t.test(x ~ GSE114922.ASpediaFI$samples$condition)$p.value)
query <- names(pvalues)[pvalues < 0.01]
head(query)
@

The \texttt{analyze} method allows the user to change options for data
preprocessing, network construction, and DRaWR. \texttt{restart} and
\texttt{num.feats} define a restart probability and the number of features to
be retained in the final subnetwork. \texttt{num.folds} specifies the number of
folds in cross-validation for DRaWR. \texttt{low.expr}, \texttt{low.var},
\texttt{prop.na}, and \texttt{prop.extreme} are options for filtering AS events.
\texttt{cor.threshold} defines a threshold of Spearman's
correlation for connecting AS event nodes and gene nodes in a heterogeneous
network. Please see help(analyzeFI) for details.
<<analyzeFI,message=FALSE,fig.height=4,fig.cap="Performance of DRaWR",fig.pos="H">>=
#Perform functional interaction analysis of AS events
GSE114922.ASpediaFI$analyze(query = query, expr = GSE114922.fpkm,
                            restart = 0.7, num.folds = 5, num.feats = 100,
                            low.expr = 1, low.var = NULL, prop.na = 0.05,
                            prop.extreme = 1, cor.threshold = 0.3)
@
Figure 2 shows an ROC plot from the cross-validation produced by the
\texttt{analyze} method. 10\% of a query gene set is held out as a test set,
and the remaining gene set is used as query. Using the converged probability
distributions after the first stage and second stage RWR, ROC curves for two
stages are computed.

%------------------------------------------------------------
\subsection{Reporting}
%------------------------------------------------------------
The \texttt{analyze} method saves top-ranked AS events and pathways in the
\texttt{as.table} and \texttt{pathway.table} fields, respectively. If the
\texttt{samples} field contains information about sample conditions
(e.g. SF3B1 mutation), the results from gene set enrichment analysis are
included in the \texttt{pathway.table} field. The column \texttt{avg.rank}
is the average rank of gene nodes in the corresponding pathway. The last column
\texttt{neighborAS} is the number of AS event nodes in the final subnetwork
connected to the pathway.
<<analysisResult,message=FALSE>>=
#Table of AS nodes in the final subnetwork
head(GSE114922.ASpediaFI$as.table, 5)

#Table of GS nodes in the final subnetwork
head(GSE114922.ASpediaFI$pathway.table, 5)
@

%------------------------------------------------------------
\subsection{Visualization}
%------------------------------------------------------------
The \texttt{visualize} method enables visualization of AS events or pathways.
If the user provides an AS event nodes as input, it produces a plot
describing the AS event and a boxplot of PSI values. Note that the \texttt{gtf}
field must contain a \texttt{GRanges} object with genomic features extracted
from the GTF file. The genomic region around the AS event can be zoomed by
setting \texttt{zoom} to \texttt{TRUE}. Figure 3 illustrates the skipped exon of
HMBS, which has been shown to be associated with SF3B1 mutation in MDS.
<<VizAS,message=FALSE,fig.pos="H",fig.cap="AS event visualization",fig.height=4.5>>=
#Visualize AS event
GSE114922.ASpediaFI$visualize(node = GSE114922.ASpediaFI$as.table$node[2],
                              zoom = FALSE)
@
\pagebreak
If a pathway node is given, the \texttt{visualize} method shows a
subnetwork consisting of highly ranked gene nodes and AS event nodes connected
to the given pathway. The user can change the number of gene and AS event nodes
to be shown in the subnetwork by setting \texttt{n}. Figure 4 demonstrates the
subnetwork related to the hallmark pathway of heme metabolism which has also
been shown to be associated with SF3B1 mutation in MDS.
<<VizGS,message=FALSE,fig.pos="H",fig.cap="Pathway visulization",fig.height=5>>=
#Visualize nework pertaining to specific pathway
GSE114922.ASpediaFI$visualize(node = GSE114922.ASpediaFI$pathway.table$node[2],
                              n = 10)
@

\renewcommand{\refname}{\section{References}}
\begin{thebibliography}{1}

\bibitem{gse114922}
Pellagatti, A. et al. (2018).
\newblock Impact of spliceosome mutations on RNA splicing in myelodysplasia:
dysregulated genes/pathways and clinical associations.
\newblock {\em Blood\/}, {\bf 132}, 1225--1240.

\bibitem{drawr}
Blatti, C. et al. (2016).
\newblock Characterizing gene sets using discriminative random walks with
restart on heterogeneous biological networks.
\newblock {\em Bioinformatics\/}, {\bf 32}, 2167--2175.

\end{thebibliography}


\end{document}
